artifact_location: file:g:/Work Projects/AI & ML Projects/AI-ML-Projects/Yolov11-License
  Plate Recognition/runs/mlflow/894046848899007047
creation_time: 1763567503400
experiment_id: '894046848899007047'
last_update_time: 1763567503400
lifecycle_stage: active
name: Yolov11-License-Plate-Model
