artifact_location: file:g:/Work Projects/AI & ML Projects/AI-ML-Projects/Yolov11-License
  Plate Recognition/runs/mlflow/0
creation_time: 1763567503281
experiment_id: '0'
last_update_time: 1763567503281
lifecycle_stage: active
name: Default
