artifact_location: file:g:/Work Projects/AI & ML Projects/AI-ML-Projects/Yolov11-Wall
  & Road Cracks-Detection/runs/mlflow/0
creation_time: 1763476235781
experiment_id: '0'
last_update_time: 1763476235781
lifecycle_stage: active
name: Default
