artifact_location: file:g:/Work Projects/AI & ML Projects/AI-ML-Projects/Yolov11-Wall
  & Road Cracks-Detection/runs/mlflow/778938638826182955
creation_time: 1763476236911
experiment_id: '778938638826182955'
last_update_time: 1763476236911
lifecycle_stage: active
name: Yolov11-test
